version: "3.9"
services:
  srt-relay:
    build: muxbox/muxbox-srt-relay
    ports:
      - "1935:1935/udp"
      - "8080:8080"
  srtla-rec:
    build: muxbox/srtla-rec
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "1985:1985/udp"
    command: ["1985", "host.docker.internal", "1935"]
