name: srt-relay

on:
  push:
    branches: main

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: ./srt-relay
          file: ./srt-relay/Dockerfile
          platforms: linux/amd64
          push: true
          tags: muxfd/muxbox-srt-relay:latest
  github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./srt-relay
          file: ./srt-relay/Dockerfile
          platformss: linux/amd64
          push: true
          tags: muxfd/muxbox/srt-relay:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
